CREATE TABLE Position(	
	Id UNIQUEIDENTIFIER  NOT NULL PRIMARY KEY,
	Title VARCHAR(255),
)

CREATE TABLE Agent(	
	Id UNIQUEIDENTIFIER  NOT NULL PRIMARY KEY,
	Name VARCHAR(255),
	Surname VARCHAR(255),
	DateOfBirth DATETIME,
	DateOfStart DATETIME,
	PositionId UNIQUEIDENTIFIER,
	FOREIGN KEY (PositionId)  REFERENCES Position (Id)
)

CREATE TABLE InsuranceRate(	
	Id UNIQUEIDENTIFIER  NOT NULL PRIMARY KEY,
	BasePayment MONEY,
	UnitPayment MONEY,
)

CREATE TABLE Client(	
	Id UNIQUEIDENTIFIER  NOT NULL PRIMARY KEY,
	Name VARCHAR(255),
	Surname VARCHAR(255),
	Gender BIT, 
	DateOfBirth DATETIME,
)

CREATE TABLE InsuranceStatus(	
	Id UNIQUEIDENTIFIER  NOT NULL PRIMARY KEY,
	Status VARCHAR(255),
	Color VARCHAR(10),
)

CREATE TABLE InsuranceRequest(
	Id UNIQUEIDENTIFIER  NOT NULL PRIMARY KEY,
	DateOfStart DATETIME,
	DateOfEnd DATETIME,
	AgentId UNIQUEIDENTIFIER,
	InsuranceRateId UNIQUEIDENTIFIER,
	FOREIGN KEY (AgentId)  REFERENCES Agent (Id),
	FOREIGN KEY (InsuranceRateId)  REFERENCES InsuranceRate (Id),
)

CREATE TABLE PositionClient(
	Id UNIQUEIDENTIFIER  NOT NULL PRIMARY KEY,
	ClientId UNIQUEIDENTIFIER,
	PositionId UNIQUEIDENTIFIER,
	FOREIGN KEY (ClientId)  REFERENCES Client (Id),
	FOREIGN KEY (PositionId)  REFERENCES Position (Id),
)

CREATE TABLE Child(
	Id UNIQUEIDENTIFIER  NOT NULL PRIMARY KEY,
	Name VARCHAR(255),
	Surname VARCHAR(255),
	Age SMALLINT,
)

CREATE TABLE ClientaChildren(
	Id UNIQUEIDENTIFIER  NOT NULL PRIMARY KEY,
	ClientId UNIQUEIDENTIFIER,
	ChildId UNIQUEIDENTIFIER,
	FOREIGN KEY (ClientId)  REFERENCES Client (Id),
	FOREIGN KEY (ChildId)  REFERENCES Child (Id),
)

CREATE TABLE TypeRequest(
	Id UNIQUEIDENTIFIER  NOT NULL PRIMARY KEY,
	Title VARCHAR(255),
	CountPaymentsInYear SMALLINT,
	CountYears SMALLINT,
)

CREATE TABLE RuleRequest(
	Id UNIQUEIDENTIFIER  NOT NULL PRIMARY KEY,
	IsChildRequest BIT,
	IsOldman BIT,
	IsDisabledPerson BIT,
)

CREATE TABLE RuleTypeRequest(
	Id UNIQUEIDENTIFIER  NOT NULL PRIMARY KEY,
	RuleId UNIQUEIDENTIFIER,
	TypeId UNIQUEIDENTIFIER,
	FOREIGN KEY (RuleId)  REFERENCES RuleRequest (Id),
	FOREIGN KEY (TypeId)  REFERENCES TypeRequest (Id),
)

CREATE TABLE InsuranceSurvey(
	Id UNIQUEIDENTIFIER  NOT NULL PRIMARY KEY,
	Title VARCHAR(255),
	Description VARCHAR(1024)
)

CREATE TABLE QuestionType(
	Id UNIQUEIDENTIFIER  NOT NULL PRIMARY KEY,
	Text VARCHAR(1024)
)

CREATE TABLE Question(
	Id UNIQUEIDENTIFIER  NOT NULL PRIMARY KEY,
	Text VARCHAR(1024),
	IsMandatory BIT,
	QuestionTypeId UNIQUEIDENTIFIER,
	FOREIGN KEY (QuestionTypeId)  REFERENCES QuestionType (Id),
)

CREATE TABLE Answer(
	Id UNIQUEIDENTIFIER  NOT NULL PRIMARY KEY,
	Answer VARCHAR(1024),
	QuestionId UNIQUEIDENTIFIER,
	FOREIGN KEY (QuestionId)  REFERENCES Question (Id),
)

CREATE TABLE QuestionSurvey(
	Id UNIQUEIDENTIFIER  NOT NULL PRIMARY KEY,
	SurveyId UNIQUEIDENTIFIER,
	QuestionId UNIQUEIDENTIFIER,
	FOREIGN KEY (SurveyId)  REFERENCES RuleRequest (Id),
	FOREIGN KEY (QuestionId)  REFERENCES Question (Id),
)

CREATE TABLE AnswerValue(
	Id UNIQUEIDENTIFIER  NOT NULL PRIMARY KEY,
	Value VARCHAR(1024),
	InsuranceRequestId UNIQUEIDENTIFIER,
	FOREIGN KEY (InsuranceRequestId)  REFERENCES InsuranceRequest (Id),
	QuestionId UNIQUEIDENTIFIER,
	FOREIGN KEY (QuestionId)  REFERENCES Question (Id),
)

ALTER TABLE InsuranceRequest
ADD InsuranceStatusId UNIQUEIDENTIFIER
FOREIGN KEY (InsuranceStatusId)
REFERENCES InsuranceStatus (Id);

CREATE TABLE InsuranceTypeSurvey(
	Id UNIQUEIDENTIFIER  NOT NULL PRIMARY KEY,
	InsuranceSurveyId UNIQUEIDENTIFIER,
	FOREIGN KEY (InsuranceSurveyId)  REFERENCES InsuranceSurvey (Id),
	TypeRequestId UNIQUEIDENTIFIER,
	FOREIGN KEY (TypeRequestId)  REFERENCES TypeRequest (Id),
)

DROP TABLE InsuranceTypeSurvey;

Scaffold-DbContext "Server=(localdb)\MSSQLLocalDB;Database=InsuranceCompany;Trusted_Connection=True;" Microsoft.EntityFrameworkCore.SqlServer
